:schedule:
  request_new_users:
    every: ['45s', first_in: '0s']
    class: 'RequestNewUsersWorker'

  request_firebase_google_certificates:
    every: ['30m', first_in: '0s']
    class: 'FirebaseTasksForceWorker'